### ISSUE TITLE
can you provide method for index history data and today gainers and loosers

### ISSUE THREAD

**Issue by kb-techiepilot** [hi-imcodeman/stock-nse-india#10]

**Comment by asrafalih** [comment]
We have added helper methods. Please refer the PR below.

https://github.com/hi-imcodeman/stock-nse-india/pull/22

**Comment by asrafalih** [comment]
We couldn't pull the historical data for indices.

**Comment by asrafalih** [comment]
> We couldn't pull the historical data for indices.

We have added historical for index.

Please refer the PR https://github.com/hi-imcodeman/stock-nse-india/pull/35
