### ISSUE TITLE
Issue when running inside a docker container.

### ISSUE THREAD

**Issue by anmol5varma** [hi-imcodeman/stock-nse-india#11]
The code works perfectly on my local machine. But when I run code via docker using a HTTP call, the requests are just timing out. Any fix??

**Comment by asrafalih** [comment]
We have dockerized this App. Please refer the PR below.

https://github.com/hi-imcodeman/stock-nse-india/pull/21

**Comment by asrafalih** [comment]
Try the following things for docker.

- `docker pull imcodeman/nseindia`
- `docker run --rm -d  -p 3001:3001/tcp imcodeman/nseindia:latest`
- Then try http://localhost:3001
