### ISSUE TITLE
Encoding issue with response?

### ISSUE THREAD

**Issue by akwala** [hi-imcodeman/stock-nse-india#110]
Below is a screenshot showing the response from an API call made through the web UI of the locally running app.

![Screenshot_20241014_202637](https://github.com/user-attachments/assets/de9ec8c6-db69-4a26-93e9-e4bbfd16542a)

**Comment by kennedymca** [comment]
I am also facing the encoding response issue, please solve it soon

**Comment by karmamaster** [comment]
@akwala  @kennedymca  Pull this commit https://github.com/hi-imcodeman/stock-nse-india/pull/111, I have fixed the issue and request to merge to main branch. Waiting to @asrafalih to approve it.

**Comment by karmamaster** [comment]
You can fetch my main branch which is fixed this issue on my fork module. In case you guys urgent on it: https://github.com/karmamaster/stock-nse-india

**Comment by kennedymca** [comment]
> You can fetch my main branch which is fixed this issue on my fork module. In case you guys urgent on it: https://github.com/karmamaster/stock-nse-india

Working good, Thanks for your great support.

**Comment by karmamaster** [comment]
> > You can fetch my main branch which is fixed this issue on my fork module. In case you guys urgent on it: https://github.com/karmamaster/stock-nse-india
> 
> Working good, Thanks for your great support.

Glad to help everyone!

**Comment by kennedymca** [comment]
> > > You can fetch my main branch which is fixed this issue on my fork module. In case you guys urgent on it: https://github.com/karmamaster/stock-nse-india
> > 
> > 
> > Working good, Thanks for your great support.
> 
> Glad to help everyone!

Not receiving responses all the time, some time it is taking long time and request got failed, i am using node 12.22.12

**Comment by karmamaster** [comment]
> > > > You can fetch my main branch which is fixed this issue on my fork module. In case you guys urgent on it: https://github.com/karmamaster/stock-nse-india
> > > 
> > > 
> > > Working good, Thanks for your great support.
> > 
> > 
> > Glad to help everyone!
> 
> Not receiving responses all the time, some time it is taking long time and request got failed, i am using node 12.22.12

Sometime your ip will be temporarily limiting on access to NSE india server if you request it frequently. Just refresh the cookie then it will work.

**Comment by karmamaster** [comment]
@akwala Do my commit working with you? If yes please close the ticket

**Comment by akwala** [comment]
> @akwala Do my commit working with you? If yes please close the ticket

@karmamaster Yes, thank you, the issue is fixed in your fork. 

Closing the ticket would mean it's fixed in this repo, which would be inaccurate until your pull request is accepted.

**Comment by kennedymca** [comment]
> > > > > You can fetch my main branch which is fixed this issue on my fork module. In case you guys urgent on it: https://github.com/karmamaster/stock-nse-india
> > > > 
> > > > 
> > > > Working good, Thanks for your great support.
> > > 
> > > 
> > > Glad to help everyone!
> > 
> > 
> > Not receiving responses all the time, some time it is taking long time and request got failed, i am using node 12.22.12
> 
> Sometime your ip will be temporarily limiting on access to NSE india server if you request it frequently. Just refresh the cookie then it will work.

Please let me know, how to refresh the cookie?

**Comment by karmamaster** [comment]
> > > > > > You can fetch my main branch which is fixed this issue on my fork module. In case you guys urgent on it: https://github.com/karmamaster/stock-nse-india
> > > > > 
> > > > > 
> > > > > Working good, Thanks for your great support.
> > > > 
> > > > 
> > > > Glad to help everyone!
> > > 
> > > 
> > > Not receiving responses all the time, some time it is taking long time and request got failed, i am using node 12.22.12
> > 
> > 
> > Sometime your ip will be temporarily limiting on access to NSE india server if you request it frequently. Just refresh the cookie then it will work.
> 
> Please let me know, how to refresh the cookie?

you can recreate the module object then your cookie will be refresh. I will implement new api to refresh cookie soon in my forked module.

**Comment by karmamaster** [comment]
I will continue update this lib on my fork in future. So If anyone seeking my help please create the issue directly on the fork module.

Thank you

**Comment by asrafalih** [comment]
This issue fixed under this.

https://github.com/hi-imcodeman/stock-nse-india/pull/114

@karmamaster Please take a look on this PR.
