### ISSUE TITLE
/api/equity/historical/{symbol}

### ISSUE THREAD

**Issue by retinodesdeepak** [hi-imcodeman/stock-nse-india#44]
Hello Sir
/api/equity/historical/{symbol}
This api is not working, some time its work fine but suddenly stop working and return error.
![image](https://user-images.githubusercontent.com/88763125/187029994-62d751a2-5b81-44aa-b151-88bc94df4e53.png)

**Comment by asrafalih** [comment]
Hi @retinodesdeepak,

I have tried te link below for multiple times. I couldn't see any issues now.

https://stock-nse-india.herokuapp.com/api/equity/historical/AAVAS?dateStart=2022-08-01&dateEnd=2022-08-31

It seems intermittent issues from nseindia server. Please try again.
