### ISSUE TITLE
Histirical api not response data before 1 june 2022

### ISSUE THREAD

**Issue by retinodesdeepak** [hi-imcodeman/stock-nse-india#48]
Hi
Historical data api get response from 1 june 2022, Before this not response any data.
https://www.nseindia.com/api/historical/cm/equity?symbol=AAVAS&series=[%22EQ%22]&from=01-04-2022&to=30-05-2022
![image](https://user-images.githubusercontent.com/88763125/198934711-68afc4c4-452b-435c-b75a-66f82cc7c2bb.png)

**Comment by asrafalih** [comment]
I don't see any issues. Seems now everything working as expected. Please check once again.
