### ISSUE TITLE
Can we get PE and PB ratio for a stock?

### ISSUE THREAD

**Issue by kugesh-Rajasekaran** [hi-imcodeman/stock-nse-india#56]

**Comment by asrafalih** [comment]
You can get `Symbol P/E` and `Sectoral Index P/E` through `/api/equity/{symbol}` API call.

Use `pdSectorPe` and `pdSymbolPe` under equity metadata.

Refer: https://hi-imcodeman.github.io/stock-nse-india/interfaces/interface.equitymetadata.html
