### ISSUE TITLE
[Feature Request] Can we handle download and handle csv file for historical data i got some nse links for csv

### ISSUE THREAD

**Issue by dEvAshirvad** [hi-imcodeman/stock-nse-india#61]
https://www.nseindia.com/api/historical/cm/equity?symbol=TATAMOTORS&series=[%22EQ%22]&from=17-03-2023&to=17-04-2023&csv=true

Above link downloads csv for perticular stock like tata motors and perticular time frame.

Problems : I tried to fetch but denies after some time.

My logic is to downlod -> read ->delete it will make fetching historical data more fast.. i guess

I really want to work on this logic with you please guide me..

**Comment by asrafalih** [comment]
Sorry for the delay. You can achieve this through direct api call.

```javascript
// import { NseIndia } from 'stock-nse-india'

const {
    NseIndia
} = require('stock-nse-india')

const nse = new NseIndia()

nse.getDataByEndpoint('/api/historical/cm/equity?symbol=TATAMOTORS&series=%5B%22EQ%22%5D&from=17-03-2023&to=17-04-2023&csv=true').then(console.log)
```

Refer: https://hi-imcodeman.github.io/stock-nse-india/classes/index.nseindia.html#getdatabyendpoint

Tested in RunKit: https://runkit.com/embed/7elpmyicq2vj

**Comment by asrafalih** [comment]
> Sorry for the delay. You can achieve this through direct api call.
> 
> ```js
> // import { NseIndia } from 'stock-nse-india'
> 
> const {
>     NseIndia
> } = require('stock-nse-india')
> 
> const nse = new NseIndia()
> 
> nse.getDataByEndpoint('/api/historical/cm/equity?symbol=TATAMOTORS&series=%5B%22EQ%22%5D&from=17-03-2023&to=17-04-2023&csv=true').then(console.log)
> ```
> 
> Refer: https://hi-imcodeman.github.io/stock-nse-india/classes/index.nseindia.html#getdatabyendpoint
> 
> Tested in RunKit: https://runkit.com/embed/7elpmyicq2vj

Hope this solution works for you.
