### ISSUE TITLE
Moment range error Typeerror: cannot set properties of undefined (setting 'range')

### ISSUE THREAD

**Issue by ManasMadrecha** [hi-imcodeman/stock-nse-india#63]
## Reproduction

Install the library in any normal Vue or Nuxt app

```bash
npm i stock-nse-india
```

Use it in any vue component

```html
<script lang="ts" setup>
import {NseIndia} from "stock-nse-india"
// no error

const nseIndia = new NseIndia()
// throws an error
// moment range typeerror: cannot set properties of undefined (setting 'range') 

</script>
```

## Related or Possible solutions

- https://stackoverflow.com/a/51573253

**Comment by asrafalih** [comment]
Please check the fix https://github.com/hi-imcodeman/stock-nse-india/blob/63d5ecfff94c4e6c6822c4cf7f0256e10315876b/src/utils.ts#L1

**Comment by asrafalih** [comment]
This package is not for frontend apps. Only for node js applications.

**Comment by ManasMadrecha** [comment]
Nuxt is server rendered framework (full stack, not just frontend). I guess on client fetch, the package should not work. But on first hard reload, the package should work, as Nuxt serves initial content via server.
