### ISSUE TITLE
not working in heoku

### ISSUE THREAD

**Issue by kb-techiepilot** [hi-imcodeman/stock-nse-india#7]
I tired a simple app, working fine in my local setup, while trying to host from heroku not working

**Comment by asrafalih** [comment]
Sometimes NSE india blacklist some of the IPs of AWS, GCP, etc..

Can you try curl nseindia.com from heroku server?

**Comment by kb-techiepilot** [comment]
can you suggest me any free hosting service which can support by nseindia?

**Comment by asrafalih** [comment]
Please try the below PR for this issue.

https://github.com/hi-imcodeman/stock-nse-india/pull/23
