### ISSUE TITLE
Data Fetch is not Working in Android 

### ISSUE THREAD

**Issue by Belikekhan** [hi-imcodeman/stock-nse-india#70]
I am developing a App in React-native my code is run perfectly in IOS but not in Android

const nseIndia = new NseIndia();
  const Fetch_Single_Symbol = async () => {
    try {
      const updatedStockDetails = [];

      for (let index = 0; index < watchList.length; index++) {
        const data = watchList[index];
        const details = await nseIndia.getEquityDetails(data);
        updatedStockDetails.push(details);
      }

      setStockDetails(updatedStockDetails);
    } catch (error) {
      console.error("Error fetching equity details:", error);
    }
  };

**Comment by asrafalih** [comment]
This package is not for frontend apps. Only for node js applications.
